// Shared by scripts/build-catalog.mjs, scripts/validate-content.mjs and
// scripts/check-content-split.mjs: reads the site's study content the way the
// browser does.
//
//   docs/data.js            SUBJECTS and FOUNDATIONS (hand-edited, eager)
//   docs/content/<CODE>.js  one subject's modules, cards, questions and drills
//                           (hand-edited, loaded on demand)
//   docs/catalog.js         titles, descriptions and counts for every subject
//                           (generated from the two above, eager)
//
// See docs/content/README.md.

import { readFileSync, readdirSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import vm from "node:vm";

// Run a plain browser script (top-level consts, no exports) and hand back the
// named bindings. `globals` are visible to the script.
export function runBrowserScript(src, file, names, globals = {}) {
  const ctx = vm.createContext({ ...globals });
  vm.runInContext(`${src}\n;globalThis.__out = { ${names.join(", ")} };`, ctx, { filename: file });
  return ctx.__out;
}

export function loadSubjects(repoRoot) {
  const file = path.join(repoRoot, "docs/data.js");
  return runBrowserScript(readFileSync(file, "utf8"), file, ["SUBJECTS", "FOUNDATIONS"]);
}

// Every docs/content/<CODE>.js, run with a registerContent() that records
// what it registers. Returns { code: { file, text, hash, modules, questions,
// drills } } and a list of errors (a file that fails to run, registers the
// wrong code, or registers nothing).
export function loadContentFiles(repoRoot) {
  const dir = path.join(repoRoot, "docs/content");
  const out = {};
  const errors = [];
  for (const name of readdirSync(dir).filter((f) => f.endsWith(".js")).sort()) {
    const code = name.slice(0, -3);
    const file = path.join(dir, name);
    const rel = `docs/content/${name}`;
    const text = readFileSync(file, "utf8");
    const registered = [];
    try {
      runBrowserScript(text, file, [], { registerContent: (c, data) => registered.push([c, data]) });
    } catch (e) {
      errors.push(`${rel}: failed to parse/execute -- ${e.message}`);
      continue;
    }
    if (registered.length !== 1) {
      errors.push(`${rel}: must call registerContent() exactly once (called ${registered.length} times)`);
      continue;
    }
    const [c, data] = registered[0];
    if (c !== code) {
      errors.push(`${rel}: registers "${c}", but the file name says "${code}"`);
      continue;
    }
    out[code] = {
      file: rel,
      text,
      hash: contentHash(text),
      modules: data.modules || [],
      questions: data.questions || [],
      drills: data.drills || [],
    };
  }
  return { content: out, errors };
}

// Short, stable version tag for ?v= cache busting. Line endings are
// normalised so a Windows checkout (CRLF) and CI (LF) agree.
export function contentHash(text) {
  return createHash("sha256").update(text.replace(/\r\n/g, "\n")).digest("hex").slice(0, 10);
}

// The generated docs/catalog.js, as text. Subjects follow SUBJECTS order.
export function catalogSource(subjects, content, diagramsText, calcDrills = {}) {
  const codes = Object.keys(subjects).filter((c) => content[c]);
  const q = (s) => JSON.stringify(s);
  const body = codes
    .map((code) => {
      const c = content[code];
      const drillsBy = {};
      const drills = c.drills.concat(calcDrills[code] || []);
      drills.forEach((d) => (drillsBy[d.module] = (drillsBy[d.module] || 0) + 1));
      const hotspots = c.drills.some((d) => d.type === "hotspot");
      const mods = c.modules
        .map(
          (m) =>
            `      { id: ${q(m.id)}, title: ${q(m.title)}, description: ${q(m.description || "")}, cards: ${(m.cards || []).length}, drills: ${drillsBy[m.id] || 0} },`
        )
        .join("\n");
      return `  ${code}: {
    file: "content/${code}.js?v=${c.hash}",
    questions: ${c.questions.length},
    drills: ${drills.length},${hotspots ? "\n    diagrams: true," : ""}
    modules: [
${mods}
    ],
  },`;
    })
    .join("\n");
  return `// GENERATED by scripts/build-catalog.mjs from docs/content/*.js -- do not
// edit by hand: edit the content file, then run
//   node scripts/build-catalog.mjs
//
// Everything the site needs to know about each subject's content before that
// content has loaded: module titles and descriptions, how many cards and
// drills each module has, and how many practice questions the subject has.
// The home page, route map, dashboard, planner and due-card counts all run
// from this; a subject's own content/<CODE>.js file (cards, questions,
// drills) is fetched when a page needs its text. \`file\` carries a hash of
// the content file, so editing it changes the URL and busts caches.
const CATALOG = {
${body}
};

// Hotspot drills draw these diagrams; loaded alongside any subject whose
// catalog entry says \`diagrams: true\`.
const DIAGRAMS_FILE = "diagrams.js?v=${contentHash(diagramsText)}";
`;
}

export function buildCatalog(repoRoot) {
  const { SUBJECTS } = loadSubjects(repoRoot);
  const { content, errors } = loadContentFiles(repoRoot);
  for (const code of Object.keys(content)) {
    if (!SUBJECTS[code]) errors.push(`docs/content/${code}.js: ${code} has no SUBJECTS entry in docs/data.js`);
  }
  const diagramsText = readFileSync(path.join(repoRoot, "docs/diagrams.js"), "utf8");
  const calcFile = path.join(repoRoot, "docs/calc-drills.js");
  const { CALC_DRILLS } = runBrowserScript(readFileSync(calcFile, "utf8"), calcFile, ["CALC_DRILLS"]);
  const catalog = catalogSource(SUBJECTS, content, diagramsText, CALC_DRILLS);
  const indexFile = path.join(repoRoot, "docs/index.html");
  const index = readFileSync(indexFile, "utf8");
  const indexOut = index.replace(/catalog\.js\?v=[0-9a-f]*/, `catalog.js?v=${contentHash(catalog)}`);
  return { SUBJECTS, content, errors, catalog, index, indexOut };
}
